image: gradle:8-jdk17-alpine

before_script:
  - chmod a+x gradlew

stages:
  - build
  - verify
  - deploy

compile:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/classes/**
      - build/libs/*.jar

unit:
  stage: verify
  dependencies:
    - compile
  script:
    - ./gradlew test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    reports:
      junit: build/test-results/test/**.xml
    paths:
      - build/reports/jacoco/jacocoAggregatedReport/html/

publish:
  stage: deploy
  script:
    - ./gradlew publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

jar:
  stage: deploy
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  when: manual

badges:
  stage: deploy
  script:
    - apt-get -qq update
    - apt-get -qq install python3 python3-pip --yes
    - pip3 install anybadge
    - ./gradlew build -q
    - anybadge -l spigot -v "$(./gradlew spigotVersion -q)" -f spigot.svg -c "#007ec6"
    - anybadge -l atsArguments -v "$(./gradlew argumentsVersion -q)" -f arguments.svg -c "#007ec6"
  artifacts:
    paths:
      - spigot.svg
      - arguments.svg
    expire_in: 4 weeks
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

pages:
  stage: deploy
  dependencies:
    - unit
  script:
    - mv build/reports/jacoco/jacocoAggregatedReport/html/ public/
  artifacts:
    paths:
      - public/**
  only:
    - main
  when: manual
