/*
 * Copyright Andret (c) 2018-2021. Copying and modifying allowed only keeping git link reference.
 */

plugins {
	id 'de.jansauer.printcoverage' version '2.0.0'
	id 'com.github.johnrengelman.shadow' version '7.0.0'
	id 'kr.entree.spigradle' version '2.2.4'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_16
targetCompatibility = JavaVersion.VERSION_16

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://gitlab.com/api/v4/projects/12063927/packages/maven' }
	maven { url 'https://maven.sk89q.com/artifactory/repo' }
}

dependencies {
	compileOnly(group: 'org.spigotmc', name: 'spigot-api', version: "${spigotVersion}-R0.1-SNAPSHOT") {
		exclude group: 'com.google.code.gson', module: 'gson'
	}
	compileOnly group: 'org.projectlombok', name: 'lombok', version: lombokVersion
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '20.1.0'
	compileOnly(group: 'com.sk89q.worldedit', name: 'worldedit-bukkit', version: '7.2.3') {
		exclude group: 'com.google.code.gson', module: 'gson'
	}
	implementation group: 'eu.andret', name: 'ats-arguments', version: argumentsVersion
	implementation group: 'org.bstats', name: 'bstats-bukkit', version: '2.2.1'
	implementation group: 'com.google.code.gson', name: 'gson', version: '2.8.8'
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombokVersion

	testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.7.0'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.7.0'
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'
compileTestJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

spigot {
	authors = ['Andret']
	apiVersion = '1.16'
	description = 'A plugin creating and play parkours.'
	version = project.version
	depends = ['WorldEdit']
	prefix = 'atsParkour'

	//noinspection GroovyAssignabilityCheck
	commands {
		parkour {
			aliases = ['pk']
			description = 'The atsParkour command'
		}
	}

	//noinspection GroovyAssignabilityCheck
	permissions {
		'ats.parkour.*' {
			children = [
					'ats.parkour.help'           : true,
					'ats.parkour.create'         : true,
					'ats.parkour.remove'         : true,
					'ats.parkour.rename'         : true,
					'ats.parkour.info'           : true,
					'ats.parkour.setSpawn'       : true,
					'ats.parkour.recreate'       : true,
					'ats.parkour.start'          : true,
					'ats.parkour.stop'           : true,
					'ats.parkour.addCheckpoint'  : true,
					'ats.parkour.setCheckpoint'  : true,
					'ats.parkour.addWall'        : true,
					'ats.parkour.setWall'        : true,
					'ats.parkour.list'           : true,
					'ats.parkour.ignore'         : true,
					'ats.parkour.sprintForced'   : true,
					'ats.parkour.alwaysSpawn'    : true,
					'ats.parkour.savingResults'  : true,
					'ats.parkour.ignoreRecords'  : true,
					'ats.parkour.damageAllowed'  : true,
					'ats.parkour.effects'        : true,
					'ats.parkour.setEffect'      : true,
					'ats.parkour.boat'           : true,
					'ats.parkour.enabled'        : true,
					'ats.parkour.modifyInventory': true,
					'ats.parkour.recordsBlock'   : true,
					'ats.parkour.teleportBlock'  : true,
					'ats.parkour.teleport'       : true,
					'ats.parkour.fix'            : true,
					'ats.parkour.color'          : true,
					'ats.parkour.difficulty'     : true,
					'ats.parkour.type'           : true,
					'ats.parkour.displayName'    : true,
					'ats.parkour.authors'        : true,
					'ats.parkour.vip'            : true,
					'ats.parkour.bronze'         : true,
					'ats.parkour.silver'         : true,
					'ats.parkour.gold'           : true,
					'ats.parkour.platinum'       : true,
			]
		}
	}
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestCoverageVerification, printCoverage
}

jacoco {
	toolVersion = '0.8.7'
}

jacocoTestReport {
	reports.xml.enabled true
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0
			}
		}
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options {
		setMemberLevel JavadocMemberLevel.PUBLIC
		setAuthor true

		links 'https://docs.oracle.com/en/java/javase/11/docs/api/'
	}
}

task sourceJar(type: Jar) {
	archiveClassifier.set('sources')
	from file('build/delombok')
}

task packageJavadoc(type: Jar) {
	archiveClassifier.set('javadoc')
	from javadoc
}

publishing {
	publications {
		//noinspection GroovyAssignabilityCheck
		library(MavenPublication) {
			from components.java
			artifact tasks.sourceJar
			artifact tasks.packageJavadoc
			groupId = project.group
			version = project.version
			artifactId = project.codeName
		}
	}
	repositories {
		maven {
			url 'https://gitlab.com/api/v4/projects/6426481/packages/maven'
			credentials(HttpHeaderCredentials) {
				name = 'Job-Token'
				value = System.getenv('CI_JOB_TOKEN')
			}
			authentication {
				//noinspection GroovyAssignabilityCheck
				header(HttpHeaderAuthentication)
			}
		}
	}
}

shadowJar {
	dependencies {
		exclude(dependency('com.google.code.gson:gson:2.8.0'))
	}
	archiveFileName = "${project.name}-${project.version}.jar"
	relocate 'org.json', 'eu.andret.ats.parkour.json'
	relocate 'eu.andret.arguments', 'eu.andret.ats.parkour.arguments'
	relocate 'org.bstats', 'eu.andret.ats.parkour.bstats'
	relocate 'com.google.gson', 'eu.andret.ats.parkour.gson'
	project.configurations.implementation.canBeResolved = true
	configurations = [project.configurations.implementation]
}

build.dependsOn(shadowJar)

task delombok {
	dependencies {
		compileOnly group: 'it.unimi.dsi', name: 'fastutil', version: '8.2.1'
	}
	project.configurations.compileOnly.canBeResolved = true
	ant.taskdef(classname: 'lombok.delombok.ant.Tasks$Delombok', classpath: configurations.compileOnly.asPath, name: 'delombok')
	ant.mkdir(dir: 'build/delombok')
	ant.delombok(verbose: 'true', encoding: 'UTF-8', to: 'build/delombok', from: 'src/main/java')
}

tasks.register('spigotVersion') {
	doLast {
		println(spigotVersion)
	}
}

tasks.register('argumentsVersion') {
	doLast {
		println(argumentsVersion)
	}
}

tasks.register('version') {
	doLast {
		println(version)
	}
}
