/*
 * Copyright Andret (c) 2019-2021. Copying and modifying allowed only keeping git link reference.
 */

import io.franzbecker.gradle.lombok.task.DelombokTask

buildscript {
	repositories {
		maven { url 'https://plugins.gradle.org/m2/' }
	}
	dependencies { classpath 'io.franzbecker:gradle-lombok:2.0' }
}

plugins {
	id 'de.jansauer.printcoverage' version '2.0.0'
	id 'com.github.johnrengelman.shadow' version '6.1.0'
	id 'kr.entree.spigradle' version '2.2.3'
	id 'io.franzbecker.gradle-lombok' version '4.0.0'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://gitlab.com/api/v4/projects/12063927/packages/maven' }
	maven { url "https://maven.sk89q.com/artifactory/repo" }
}

dependencies {
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: "${spigotVersion}-R0.1-SNAPSHOT"
	compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.18'
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '20.1.0'
	compileOnly group: 'com.sk89q.worldedit', name: 'worldedit-bukkit', version: '7.2.3'
	implementation group: 'eu.andret', name: 'ats-arguments', version: argumentsVersion
	implementation group: 'org.bstats', name: 'bstats-bukkit', version: '2.2.1'
	implementation group: 'org.json', name: 'json', version: '20210307'
	annotationProcessor group: "org.projectlombok", name: "lombok", version: "1.18.18"

	testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.7.0'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.7.0'
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'
compileTestJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

spigot {
	authors = ['Andret']
	apiVersion = '1.16'
	description = 'A plugin creating and play parkours.'
	version = project.version
	depends = ['WorldEdit']
	softDepends = ['Multiverse']
	prefix = 'atsParkour'

	//noinspection GroovyAssignabilityCheck
	commands {
		parkour {
			aliases = ['pk']
			description = 'The atsParkour command'
		}
	}

	//noinspection GroovyAssignabilityCheck
	permissions {
		'ats.parkour.*' {
			children = [
					'ats.parkour.help'           : true,
					'ats.parkour.create'         : true,
					'ats.parkour.remove'         : true,
					'ats.parkour.rename'         : true,
					'ats.parkour.info'           : true,
					'ats.parkour.setSpawn'       : true,
					'ats.parkour.recreate'       : true,
					'ats.parkour.start'          : true,
					'ats.parkour.stop'           : true,
					'ats.parkour.addCheckpoint'  : true,
					'ats.parkour.setCheckpoint'  : true,
					'ats.parkour.addWall'        : true,
					'ats.parkour.setWall'        : true,
					'ats.parkour.list'           : true,
					'ats.parkour.ignore'         : true,
					'ats.parkour.sprintForced'   : true,
					'ats.parkour.alwaysSpawn'    : true,
					'ats.parkour.savingResults'  : true,
					'ats.parkour.ignoreRecords'  : true,
					'ats.parkour.damageAllowed'  : true,
					'ats.parkour.effects'        : true,
					'ats.parkour.setEffect'      : true,
					'ats.parkour.boat'           : true,
					'ats.parkour.enabled'        : true,
					'ats.parkour.modifyInventory': true,
					'ats.parkour.recordsBlock'   : true,
					'ats.parkour.teleportBlock'  : true,
					'ats.parkour.teleport'       : true,
					'ats.parkour.fix'            : true,
					'ats.parkour.color'          : true,
					'ats.parkour.difficulty'     : true,
					'ats.parkour.type'           : true,
					'ats.parkour.displayName'    : true,
					'ats.parkour.authors'        : true,
					'ats.parkour.vip'            : true,
					'ats.parkour.bronze'         : true,
					'ats.parkour.silver'         : true,
					'ats.parkour.gold'           : true,
					'ats.parkour.platinum'       : true,
			]
		}
	}
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestCoverageVerification, printCoverage
}

jacocoTestReport {
	reports.xml.enabled true
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0
			}
		}
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options {
		setMemberLevel JavadocMemberLevel.PUBLIC
		setAuthor true

		links 'https://docs.oracle.com/en/java/javase/11/docs/api/'
	}
}

task sourceJar(type: Jar) {
	archiveClassifier.set('sources')
	from sourceSets.main.allJava
}

task packageJavadoc(type: Jar) {
	archiveClassifier.set('javadoc')
	from javadoc
}

publishing {
	publications {
		//noinspection GroovyAssignabilityCheck
		library(MavenPublication) {
			from components.java
			artifact tasks.sourceJar
			artifact tasks.packageJavadoc
			groupId = project.group
			version = project.version
			artifactId = project.codeName
		}
	}
	repositories {
		maven {
			url 'https://gitlab.com/api/v4/projects/6426481/packages/maven'
			credentials(HttpHeaderCredentials) {
				name = 'Job-Token'
				value = System.getenv('CI_JOB_TOKEN')
			}
			authentication {
				//noinspection GroovyAssignabilityCheck
				header(HttpHeaderAuthentication)
			}
		}
	}
}

shadowJar {
	archiveFileName = "${project.name}-${project.version}.jar"
	relocate 'org.json', 'eu.andret.ats.parkour.json'
	relocate 'eu.andret.arguments', 'eu.andret.ats.parkour.arguments'
	relocate "org.bstats", "eu.andret.ats.parkour.bstats"
	project.configurations.implementation.canBeResolved = true
	configurations = [project.configurations.implementation]
}

build.dependsOn(shadowJar)

task delombok(type: DelombokTask, dependsOn: compileJava) {
	ext.outputDir = file("$buildDir/delombok")
	outputs.dir(outputDir)
	sourceSets.main.java.srcDirs.each {
		inputs.dir(it)
		args(it, '-d', outputDir)
	}
	doFirst { outputDir.deleteDir() }
}

tasks.register('spigotVersion') {
	doLast {
		println(spigotVersion)
	}
}

tasks.register('argumentsVersion') {
	doLast {
		println(argumentsVersion)
	}
}

tasks.register('version') {
	doLast {
		println(version)
	}
}
