connection:
  url: localhost
  user: root
  pass: ''
  dbname: ats_parkour
door:
  name: 'Exit!'
  lore: 'Click it/nto exit.'
lobby:
  world: -1
  x: -1
  y: -1
  z: -1
  yaw: -1
  pitch: -1
recordSign:
  line1: '&2&lREKORD'
  line2: '%MINUTES%:%SECONDS%.%MILISECONDS%'
  line3: '%NICK%'
  line4: ''
last-checkpoint-info: false
medal:
  platinum: 'platinum'
  gold: 'gold'
  silver: 'silver'
  bronze: 'bronze'
  none: 'none'
