/*
 * Copyright Andret (c) 2018. Copying and modifying allowed only keeping git link reference.
 */

plugins {
	id 'kr.entree.spigradle'
	id 'com.github.johnrengelman.shadow'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_16
targetCompatibility = JavaVersion.VERSION_16

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://gitlab.com/api/v4/projects/12063927/packages/maven' }
}

dependencies {
	compileOnly rootProject
	compileOnly group: 'org.projectlombok', name: 'lombok', version: rootProject.lombokVersion
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: "${rootProject.spigotVersion}-R0.1-SNAPSHOT"
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'
	implementation group: 'eu.andret', name: 'ats-arguments', version: rootProject.argumentsVersion
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: rootProject.lombokVersion
}

compileJava.dependsOn rootProject.tasks.jar

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

spigot {
	authors = ['Andret']
	apiVersion = '1.17'
	description = 'A sample plugin to test exposed mechanics'
	version = project.version
	depends = ['atsParkour']
	libraries = []

	//noinspection GroovyAssignabilityCheck
	commands {
		sample {
			description = 'The atsParkourSample command'
		}
	}
}

shadowJar {
	archiveFileName = "${project.name}-${project.version}.jar"
	relocate 'eu.andret.arguments', 'eu.andret.ats.parkour.sample.arguments'
}

build.dependsOn(shadowJar)

project.tasks.publish.enabled = false
