buildscript {
	repositories {
		maven { url 'https://plugins.gradle.org/m2/' }
	}
}

plugins {
	id 'kr.entree.spigradle'
	id 'com.github.johnrengelman.shadow'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
	mavenLocal()
	mavenCentral()
	maven { url 'https://gitlab.com/api/v4/projects/12063927/packages/maven' }
}

dependencies {
	compileOnly rootProject
	compileOnly group: 'org.projectlombok', name: 'lombok', version: lombokVersion
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: "${rootProject.spigotVersion}-R0.1-SNAPSHOT"
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '20.1.0'
	implementation group: 'eu.andret', name: 'ats-arguments', version: rootProject.argumentsVersion
	annotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

spigot {
	authors = ['Andret']
	apiVersion = '1.16'
	description = 'A sample plugin to test exposed mechanics'
	version = project.version
	depends = ['atsParkour']
	prefix = 'atsParkourSample'

	//noinspection GroovyAssignabilityCheck
	commands {
		sample {
			description = 'The atsParkourSample command'
		}
	}
}

shadowJar {
	archiveFileName = "${project.name}-${project.version}.jar"
	relocate 'eu.andret.arguments', 'eu.andret.ats.parkour.sample.arguments'
	project.configurations.implementation.canBeResolved = true
	configurations = [project.configurations.implementation]
}

build.dependsOn(shadowJar)

project.tasks.publish.enabled = false
