name: atsParkour
main: eu.andret.atsparkour.atsParkour
version: 1.7
author: Andret
depend: [WorldEdit]
softdepend: [Multiverse, LobbyCoins, GlobalPermissions]

commands:
  parkour:
    description: The Parkour command
    aliases: [pk, sr, speedrun]
  hub:
    description: back to main server
    aliases: [lobby, wyjscie, exit]

permissions:
  ats.parkour.*:
    children:
      ats.parkour.main: true
      ats.parkour.create: true
      ats.parkour.setspawn: true
      ats.parkour.addcheckpoint: true
      ats.parkour.setcheckpoint: true
      ats.parkour.start: true
      ats.parkour.recreate: true
      ats.parkour.stop: true
      ats.parkour.ignore: true
      ats.parkour.list: true
      ats.parkour.addwall: true
      ats.parkour.setwall: true
      ats.parkour.setwall: true
      ats.parkour.sprint: true
      ats.parkour.price: true
      ats.parkour.alwaysspawn: true
      ats.parkour.countrecords: true
      ats.parkour.modify: true
      ats.parkour.damage: true
      ats.parkour.help: true
      ats.parkour.boats: true
      ats.parkour.effect: true
      ats.parkour.bronze: true
      ats.parkour.silver: true
      ats.parkour.gold: true
      ats.parkour.platinium: true
      ats.parkour.effectregion: true
      ats.parkour.rename: true
      ats.parkour.teleportblock: true
      ats.parkour.teleport: true
      ats.parkour.ignorerecords: true
      ats.parkour.available: true
      ats.parkour.type: true
      ats.parkour.displayname: true
      ats.parkour.vip: true
      ats.parkour.spectator: true
      ats.parkour.fix: true
      ats.parkour.proceedable: true
      ats.parkour.fair: true
      ats.parkour.xp: true